名字: Android CI

在:
推:
分支: [ “主要” ]
拉取请求:
分支: [ “主要” ]

工作:
建设:

连续运行: Ubuntu-最新版

步伐:
    - 使用: 动作/签出@v3
    - 名字: 建立JDK 11号
使用: 操作/设置-java@v3
随着:
java版本: '11'
分布: 特穆林
隐藏物: 格拉德勒

    - 名字: 授予gradlew执行权限
奔跑: chmod +x gradlew
    - 名字: 与Gradle一起构建
奔跑: 。/gradlew版本
